name: Web Scraping and API Update

on:
  schedule:
    - cron: '0 0-3 * * 0-4'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run app.py
        env:
          API_KEY: ${{ secrets.API_KEY }} 
        run: python app.py